version: '2'

services:
    web:
        container_name: web
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html:rw
            - ./docker/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-fpm
        links:
            - php-fpm
    php-fpm:
        container_name: php-fpm
        build:
            context: .
            dockerfile: Dockerfile
            args:
                USER_ID: '${USER_ID}'
                GROUP_ID: '${GROUP_ID}'
        volumes:
            - ./:/var/www/html:rw
        links:
            - db
    db:
        image: mysql:5.7
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: app_db
            MYSQL_USER: db_user
            MYSQL_PASSWORD: db_user_pass
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - "8080:80"
volumes:
    dbdata:
